### ISSUE TITLE
Android app for notes keeps crashing when saved

### ISSUE THREAD

**Issue by hitchhooker** [etesync/etesync-notes#151]
Android app downloaded from Google store keeps crashing on MiUI 11 android10 Xiaomi redmi 9.

Error report:

`com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 't.cache'), stack:
<unknown>@1069:1910
<unknown>@1076:25591
iterate@1076:29450
__iterate@1076:25757
<unknown>@1076:25562
Le@1076:24025
<unknown>@1069:1858
<unknown>@1076:25591
iterate@1076:29450
__iterate@1076:25757
<unknown>@1076:25562
Le@1076:24025
<unknown>@1069:1833
reduce@-1
E@1058:486
y@133:580
callTimers@133:2629
value@28:3350
<unknown>@28:747
value@28:2610
value@28:719
value@-1

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:224)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:919)
`

Debug logs:
`[D] App switched to background
[I] ConnectionfInfo: true cellular
[D] App switched to foreground
[D] App switched to background
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[I] ConnectionfInfo: true cellular
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[I] ConnectionfInfo: true cellular
[D] App switched to foreground`

**Comment by hitchhooker** [comment]
`null is not an object (evaluating 'n.getCollectionManager')
/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:1004:2418
y@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:112:587
/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:112:1890
y@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:112:587
o@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:112:1066
/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:112:1209
f@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:40:155
/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:40:864
y@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:128:581
C@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:128:947
callImmediates@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:128:3004
value@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:26:2919
/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:26:1095
value@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:26:2611
value@/data/user/0/com.etesync.notes/files/.expo-internal/bundle-6BB6030071D6D5A776B08AAC379D04C59230A14F15D253AB0A43B8B9BC5B4360:26:1065
value@[native code]
value@[native code]
[D] App switched to background
[I] ConnectionfInfo: true cellular
[D] App switched to foreground
[D] App switched to background
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[I] ConnectionfInfo: true cellular
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[I] ConnectionfInfo: true cellular
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[D] App switched to background
[D] App switched to foreground
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[I] ConnectionfInfo: true cellular
[D] App switched to foreground
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')
[I] ConnectionfInfo: true cellular
[D] App switched to foreground
[C] TypeError: undefined is not an object (evaluating 'w.isDeleted')`

**Comment by hitchhooker** [comment]
Logged out and deleted cache of the app. Logged in again and only the created note was saved in serverside but no content so possible that issue is caused by my etesync server hosted at sync.rotko.net

**Comment by zecakeh** [comment]
Thanks for the bug report! I'll try to investigate that soon. I have an idea where that could come from…

**Comment by zecakeh** [comment]
Sorry, it seems I can't reproduce that with my setup. I have a few questions to try to reproduce the error:
- Is this the first note in your account?
- Does it happen when you press `Save` in the menu or when you go back from the note ?
- Does it still crash if you try to edit the same note after a crash?
- Does it still crash if you try to edit the same note after you delete the cache?
- Did you try with another account on your server?

**Comment by hitchhooker** [comment]
yes its first note. happens both when i press save nd go back to the menu. crashes also after editing same note. even after deleting cache crashes. will try another account, i think im using admin account and its not syncing anything on the server so it is probably account or server setting related problem.

thanks a lot for troubleshooting help.
